version: '3.8'
services:
  postgres:
    image: postgres:16.6-alpine3.21
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prod
    ports:
      - "5432:5432"