version: 1
disable_existing_loggers: False
formatters:
  default:
    format: '%(asctime)s - %(levelname)s - %(message)s'
handlers:
  file:
    class: logging.FileHandler
    filename: uvicorn.log
    formatter: default
    level: INFO
  console:
    class: logging.StreamHandler
    formatter: default
    level: INFO
loggers:
  uvicorn:
    handlers: [file, console]
    level: INFO
    propagate: no
