"""валидация полей купоны

Revision ID: 5a6a9d17012c
Revises: 5249aa97e846
Create Date: 2025-01-25 14:51:25.568311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5a6a9d17012c'
down_revision: Union[str, None] = '5249aa97e846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'comments', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='unique')
    # ### end Alembic commands ###
