"""default factory для id комментариев

Revision ID: 5abd66e0ca2e
Revises: fc66de3c136a
Create Date: 2025-01-26 18:57:01.751552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5abd66e0ca2e'
down_revision: Union[str, None] = 'fc66de3c136a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
