"""обновила поля комментариев

Revision ID: fc66de3c136a
Revises: 5a6a9d17012c
Create Date: 2025-01-26 18:11:15.992767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fc66de3c136a'
down_revision: Union[str, None] = '5a6a9d17012c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('text', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False))
    op.add_column('comments', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('users', 'country',
               existing_type=sa.VARCHAR(length=10),
               type_=sqlmodel.sql.sqltypes.AutoString(length=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'country',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=2),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_column('comments', 'created_at')
    op.drop_column('comments', 'text')
    # ### end Alembic commands ###
